### ISSUE TITLE
`element_data_loader` is non-existent in this repository

### ISSUE THREAD

**Issue by tdincer** [datajoint/workflow-calcium-imaging#48]
`element_data_loader` is required both in the requirements.txt file and the documentation. Otherwise trigger won't work.

**Comment by kabilar** [comment]
Thanks @tdincer.  The pull request linked above now documents the installation instructions for `element-data-loader`.

We opted not to put `element-data-loader` in the `requirements.txt` of `workflow-calcium-imaging`, because we have configured `element-data-loader` to allow for installation of optional packages that are not on PyPI, such as CaImAn and scanreader.  This is done using the `extras_require` feature in [setup.py](https://github.com/datajoint/element-data-loader/blob/main/setup.py#L36).  The user would manually choose which optional packages they wanted to install and follow these [installation instructions](https://github.com/datajoint/element-data-loader#installation).  Thus installation of `element-data-loader` would be an extra installation step outside of `requirements.txt`.
